dist: xenial
language: generic
services:
  - docker
branches:
  only:
    - master
addons:
  apt:
    packages:
      - python3
      - python3-pip
jobs:
  include:
    - stage: testing
      name: "Run unit tests"
      before_script:
        - pip3 install pyflakes pycodestyle
        - pyflakes *.py cobbler/*.py cobbler/modules/*.py cobbler/web/*.py cobbler/web/templatetags/*.py bin/cobbler* bin/*.py web/cobbler.wsgi
        - pycodestyle -r --ignore E501,E402,E722,W504 *.py cobbler/*.py cobbler/modules/*.py cobbler/web/*.py cobbler/web/templatetags/*.py bin/cobbler* bin/*.py web/cobbler.wsgi
      script:
        - docker build -t cobbler .
        - docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name cobbler cobbler
        - sleep 30
        - docker logs cobbler
        - docker exec -u 0 -it cobbler bash -c pytest
    - stage: rpms
      name: "Build CentOS 7 RPMs"
      script: ./tests/build-and-install-rpms.sh el7 dockerfiles/CentOS7.dockerfile
    - stage: rpms
      name: "Build CentOS 8 RPMs"
      script: ./tests/build-and-install-rpms.sh el8 dockerfiles/CentOS8.dockerfile
    - stage: rpms
      name: "Build Fedora 29 RPMs"
      script: ./tests/build-and-install-rpms.sh fc29 dockerfiles/Fedora29.dockerfile
    - stage: rpms
      name: "Build Fedora 30 RPMs"
      script: ./tests/build-and-install-rpms.sh fc30 dockerfiles/Fedora30.dockerfile
