language: python
python:
 - "3.6"
branches:
 only:
  - master
addons:
  apt:
   packages:
    # We need this explicitly because if we don't install it it is not available.
    # See: https://stackoverflow.com/questions/31065550/travis-ci-cant-find-python3-pip-package
    - python3-pip
    - apache2
    - apache2-dev
    - acl
    - libapache2-mod-wsgi-py3
    - ipmitool
    - rsync
    - fence-agents
    - genders
    # mkisofs is not available on ubuntu
    - genisoimage
install:
 - sudo pip3 install -r requirements-test.txt
 - python setup.py build
 - sudo python setup.py install
before_script:
 - pyflakes *.py cobbler/*.py cobbler/modules/*.py cobbler/web/*.py cobbler/web/templatetags/*.py bin/cobbler* bin/*.py web/cobbler.wsgi
 - pycodestyle -r --ignore E501,E402,E722 *.py cobbler/*.py cobbler/modules/*.py cobbler/web/*.py cobbler/web/templatetags/*.py bin/cobbler* bin/*.py web/cobbler.wsgi
script: pytest test
