language: python
python:
 - "3.6"
branches:
 only:
  - master
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y python3-all python3-yaml git-core python3-setuptools python3-netaddr python3-nose python3-simplejson python3-pyflakes python3-pycodestyle
install:
 - "/bin/true"
script: make qa
