version: '3.7'

services:

  centos7-build:
    image: local/cobbler-centos7
    container_name: cobbler-centos7
    build:
      context: .
      dockerfile: ./dockerfiles/CentOS7.dockerfile
    volumes:
      - ./rpm-build/el7:/usr/src/cobbler/rpm-build

  centos8-build:
    image: local/cobbler-centos8
    container_name: cobbler-centos8
    build:
      context: .
      dockerfile: ./dockerfiles/CentOS8.dockerfile
    volumes:
      - ./rpm-build/el8:/usr/src/cobbler/rpm-build

  fedora33-build:
    image: local/cobbler-fedora33
    container_name: cobbler-fedora33
    build:
      context: .
      dockerfile: ./dockerfiles/Fedora33.dockerfile
    volumes:
      - ./rpm-build/f33:/usr/src/cobbler/rpm-build
